package view;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.geom.Line2D;
import controller.Game;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author foxhound
 */
public class PlayboardView extends javax.swing.JFrame {
	
	private Game game;

    /**
     * Creates new form NewJFrame
     */
    public PlayboardView() {
        initComponents();        
        game = new Game("red", "blue");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {    
    	
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(221, 65, 39, 23);

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(330, 120, 39, 23);

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(370, 200, 39, 23);
        


        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(310, 290, 39, 23);

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(220, 340, 39, 23);

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(140, 290, 39, 23);

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(70, 190, 39, 23);

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(110, 120, 39, 23);

        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(220, 200, 39, 23);
        
        infoLabel.setText("Info:");
        getContentPane().add(infoLabel);
        infoLabel.setBounds(40, 424, 870, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {      	
    	game.doStep(jButton1);    	
   	}

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
    	game.doStep(jButton2);
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	game.doStep(jButton3);
    }  

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
    	game.doStep(jButton4); 
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
    	game.doStep(jButton5); 
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
    	game.doStep(jButton6);
    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
    	game.doStep(jButton7); 
    }

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
    	game.doStep(jButton8); 
    }

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
    	game.doStep(jButton9); 
    }
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PlayboardView view = new PlayboardView();
                view.setVisible(true);
                
                view.setSize(800, 800);

                // Field locations
                view.jButton1.setLocation(350, 100);                
                view.jButton9.setLocation(350, 300);                
                view.jButton5.setLocation(350, 500);
                
                view.jButton7.setLocation(150, 300);
                view.jButton3.setLocation(550, 300);
                
                view.jButton2.setLocation(500, 200);
                view.jButton8.setLocation(200, 200);
                
                view.jButton4.setLocation(500, 400);
                view.jButton6.setLocation(200, 400);         
                
                view.infoLabel.setLocation(50, 600);
                
                       
            }
        });
    }
    
    /**
     * Draw lines
     * @param g 
     */
    public void paint (Graphics g) {
        Graphics2D g2 = (Graphics2D) g;        
       // 1 - 9
        g2.draw(new Line2D.Double(new Point(377, 150), new Point(377, 330) ));
        
        // 9 - 5
        g2.draw(new Line2D.Double(new Point(377, 350), new Point(377, 530) ));
        
        // 7 - 9
        g2.draw(new Line2D.Double(new Point(195, 340), new Point(360, 340) ));
        
        // 9 - 3
        g2.draw(new Line2D.Double(new Point(395, 340), new Point(560, 340) ));
        
        // 1 - 8
        g2.draw(new Line2D.Double(new Point(377, 150), new Point(377, 330) ));
        
        // 1 - 2
        g2.draw(new Line2D.Double(new Point(397,150), new Point(512,233) ));
        
        // 7 -8
        g2.draw(new Line2D.Double(new Point(172,327), new Point(217,253) ));
        
        // 2 - 3
        g2.draw(new Line2D.Double(new Point(530,255), new Point(576,324) ));
        
        // 3 - 4
        g2.draw(new Line2D.Double(new Point(577,354), new Point(529,429) ));
        
        // 4 - 5
        g2.draw(new Line2D.Double(new Point(526,453), new Point(398,541) ));
        
        // 7 - 6
        g2.draw(new Line2D.Double(new Point(210,429), new Point(171,353) ));
        
        // 6 - 5
         g2.draw(new Line2D.Double(new Point(355,542), new Point(226,453) ));
        
        // 8 - 1
         g2.draw(new Line2D.Double(new Point(228,227), new Point(357,141) ));
         
         // 8 - 9
         g2.draw(new Line2D.Double(new Point(248,256), new Point(357,328) ));
         
         // 9 - 4
         g2.draw(new Line2D.Double(new Point(397,352), new Point(507,428) ));
         
         // 2 - 9
         g2.draw(new Line2D.Double(new Point(507,251), new Point(397,330) ));
         
         // 9 - 6
         g2.draw(new Line2D.Double(new Point(360,354), new Point(247,433) ));         
    }

    private javax.swing.JLabel infoLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
}
